SET NAMES utf8mb4;

INSERT INTO `tins` (`id`, `state_tin`, `state`, `state_code`, `created_at`, `updated_at`) VALUES
(1,	'37',	'Andhra Pradesh	',	'AD',	NULL,	NULL),
(2,	'12',	'Arunachal Pradesh	',	'AR',	NULL,	NULL),
(3,	'18',	'Assam',	'AS',	NULL,	NULL),
(4,	'10',	'Bihar',	'BR',	NULL,	NULL),
(5,	'22',	'Chattisgarh	',	'CG',	NULL,	NULL),
(6,	'07',	'Delhi',	'DL',	NULL,	NULL),
(7,	'30',	'Goa',	'GA',	NULL,	NULL),
(8,	'24',	'Gujarat',	'GJ',	NULL,	NULL),
(9,	'06',	'Haryana',	'HR',	NULL,	NULL),
(10,	'02',	'Himachal Pradesh	',	'HP',	NULL,	NULL),
(11,	'01',	'Jammu and Kashmir',	'JK',	NULL,	NULL),
(12,	'20',	'Jharkhand',	'JH',	NULL,	NULL),
(13,	'29',	'Karnataka',	'KA',	NULL,	NULL),
(14,	'32',	'Kerala',	'KL',	NULL,	NULL),
(15,	'31',	'Lakshadweep Islands',	'LD',	NULL,	NULL),
(16,	'23',	'Madhya Pradesh	',	'MP',	NULL,	NULL),
(17,	'27',	'Maharashtra	',	'MH',	NULL,	NULL),
(18,	'14',	'Manipur	',	'MN',	NULL,	NULL),
(19,	'17',	'Meghalaya',	'ML',	NULL,	NULL),
(20,	'15',	'Mizoram',	'MZ',	NULL,	NULL),
(21,	'13',	'Nagaland',	'NL',	NULL,	NULL),
(22,	'21',	'Odisha',	'OD',	NULL,	NULL),
(23,	'34',	'Pondicherry',	'PY',	NULL,	NULL),
(24,	'03',	'Punjab	',	'PB',	NULL,	NULL),
(25,	'08',	'Rajasthan',	'RJ',	NULL,	NULL),
(26,	'11 ',	'Sikkim	',	'SK',	NULL,	NULL),
(27,	'33	',	'Tamil Nadu	',	'TN',	NULL,	NULL),
(28,	'36',	'Telangana',	'TS',	NULL,	NULL),
(29,	'16',	'Tripura',	'TR',	NULL,	NULL),
(30,	'09',	'Uttar Pradesh	',	'UP',	NULL,	NULL),
(31,	'05',	'Uttarakhand	',	'UK',	NULL,	NULL),
(32,	'19	',	'West Bengal	',	'WB',	NULL,	NULL);
